// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.junit.jupiter.api.Assertions;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Interactive;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import org.junit.jupiter.api.Assertions.*;
public class CPUS002Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private static SeleniumConfig config;
  private static String url="https://www.demoblaze.com/index.html";
  @Test
  public void cPUS002() {
    config = new SeleniumConfig();
    config.getDriver().get(url);
    WebDriver driver= config.getDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.manage().window().setSize(new Dimension(1382, 754));
    driver.findElement(By.linkText("Samsung galaxy s6")).click();
    driver.findElement(By.linkText("Add to cart")).click();
    driver.findElement(By.id("cartur")).click();
    driver.findElement(By.linkText("Delete")).click();
    driver.findElement(By.id("nava")).click();
    assertThat(driver.findElement(By.linkText("Samsung galaxy s6")).getText(), is("Samsung galaxy s6"));
  }
}
